config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers
  end

  root to: 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :questions
  has_many :answers      
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id]) 
    @answer = current_user.answers.create(answer_params) rescue nil
    # @answer = @question.answers.create(answer_params)
    if @answer == nil
      redirect_to question_path(@question), notice: "Must be signed in"
    else
      @answer.create
        redirect_to question_path(@question)
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.find(params[:id]) rescue nil
    # @answer = @question.answers.find(params[:id])
    if @answer == nil
      redirect_to question_path(@question), notice: "Can not delete another User's Answer"
    else 
      @answer.destroy
        redirect_to question_path(@question)
    end
  end
 
  private
    def answer_params
      params.require(:answer).permit(:response)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]
	
  def index
		@questions = Question.all
	end

	def show
    @question = Question.find(params[:id])
  end

	def new
    @question = Question.new
	end

  def edit
    @question = current_user.questions.find(params[:id]) rescue nil
    # @question = Question.find(params[:id])
    if @question == nil
        redirect_to questions_path, notice: "Can not change another User's Question"
    else
      @question = current_user.questions.find(params[:id])
    end
  end

	def create
		@question = current_user.questions.new(question_params) rescue nil
    # @question = Question.new(question_params)
    if @question == nil
        redirect_to questions_path, notice: "Must be signed in"
    else
    	if @question.save
    	  redirect_to @question, notice: "Question created"
      else
        render 'new'
      end
    end
  end

  def update
    @question = current_user.questions.find(params[:id]) 
    # @question = Question.find(params[:id])
    
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = current_user.questions.find params[:id] rescue nil 
    # @question = Question.find(params[:id])
    if @question == nil
        redirect_to questions_path, notice: "Can not delete another User's Question"
    else
      @question.destroy
        redirect_to questions_path
    end
  end

  private
  	def question_params
    	params.require(:question).permit(:title, :text)
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_answer.html.erb
<p>
  User:
  <strong><%= answer.user.email.split("@")[0] %></strong>
</p>
 
<p style="font-size:125%">
  A:
  <strong><%= answer.response %></strong>
</p>

<p>
  <%= link_to 'Destroy Answer', [answer.question, answer], method: :delete %>
</p>

app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  
  <p>
    <%= f.label :response %><br>
    <%= f.text_area :response %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "YahooAnswers" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">YahooAnswers</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          </ul>
          <ul class="nav navbar-nav pull-right">
           <% if current_user %>
              <li><a><%= current_user.email %></a></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

     <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
 
      <footer>
        
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
 
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p style="font-family:cookie regular">Hello <%= current_user.email.split("@")[0] rescue nil %></p>

<h1>Yahoo Questions</h1>

<%= link_to 'Create a New Question', new_question_path %>
 
<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %>&nbsp&nbsp&nbsp</td>
      <td><%= question.user.email.split("@")[0] %>&nbsp&nbsp&nbsp</td>
      <td><%= question.text %>&nbsp&nbsp&nbsp</td><p>
      <td><%= link_to 'Answers', question_path(question) %>&nbsp&nbsp&nbsp</td>
      <td><%= link_to 'Edit', edit_question_path(question) %>&nbsp&nbsp&nbsp</td>
      <td><%= link_to 'Destroy', question_path(question), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<h1>New question</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <!-- Title:
  <strong><%= @question.title %></strong> -->
<!-- </p> -->

<!-- <p> -->
  User:
  <strong><%= @question.user.email.split("@")[0] %>
  </strong>
<!-- </p> -->
 <br>
<!-- <p> -->
  
  <h1 style="font-size:125%">
  	Q: <strong><%= @question.text %></h1></strong>
</p>

<h2>------------------------------------------</h2>
<%= render @question.answers %>

<!-- <h2 style="font-size:100%">Add an Answer:</h2> -->
<%= render 'answers/form' %>

<%= link_to 'Back', questions_path %>

app/views/welcome/index.html.erb
<h2 style="font-size:300%"><%= link_to 'Yahoo Questions', controller: 'questions' %></h2>  

<p>Welcome to Yahoo!  If you want to visit our
   Yahoo Questions page, click on the link above.  <br> 
   Users must be signed in to manipulate content.  </p>